// Real profile, image, auth and review routes; AI is the named agent_server.py fixture.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const base = process.env.UI_TEST_URL || 'http://127.0.0.1:8010';
assert.equal(new URL(base).port, '8010', 'Use the disposable fixture server');
const out = path.join(os.tmpdir(), 'solvex-profiles'); fs.mkdirSync(out, {recursive:true});
const stamp = Date.now();
(async () => {
  const browser = await chromium.launch({channel:'msedge', headless:true});
  const business = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const team = await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});
  const page = await business.newPage(), teamPage = await team.newPage(), errors = [];
  [page,teamPage].forEach(p => p.on('pageerror', e => errors.push(e.message)));
  const wait = (p, selector, text) => p.waitForFunction(({selector,text}) => document.querySelector(selector)?.textContent.includes(text), {selector,text});
  async function register(context, role, name) {
    const response = await context.request.post(base+'/api/auth/register', {data:{email:name+stamp+'@example.org', password:'synthetic-password',role}});
    assert.equal(response.status(),201); return (await response.json()).csrf_token;
  }
  async function overflow(p) { const ok=await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth); if(!ok) console.log(await p.evaluate(()=>[...document.querySelectorAll('*')].map(n=>{const r=n.getBoundingClientRect();return {tag:n.tagName,id:n.id,class:n.className,right:r.right,width:r.width};}).filter(n=>n.right>innerWidth+1).slice(0,30))); assert(ok,'Page overflow'); }
  try {
    await page.goto(base); await page.locator('header [data-language]').selectOption('en');
    await wait(page,'#hero-title','breakthrough');
    await page.locator('.hero-actions [data-role="BUSINESS"]').click();
    assert.equal(await page.locator('#auth-title').innerText(), "Let's start with you");
    await page.locator('#auth-email').fill('draft'+stamp+'@example.org');
    await page.locator('.auth-dialog [data-language]').selectOption('ru');
    assert.equal(await page.locator('#auth-email').inputValue(),'draft'+stamp+'@example.org');
    await page.keyboard.press('Escape');
    const csrf = await register(business,'BUSINESS','profiles-business');
    const teamCsrf = await register(team,'TEAM','profiles-team');
    await page.goto(base+'/app#team-profile');
    await page.waitForFunction(() => !document.body.classList.contains('booting'));
    await page.locator('#team-name').fill('Название');
    await page.locator('#profile-headline').fill('Для людей и компаний');
    await page.locator('#profile-description').fill('Черновик');
    await page.locator('#profile-experience').fill('Исследование реальных процессов');
    await page.locator('#profile-industry').fill('Retail');
    await page.locator('#profile-location').fill('Almaty');
    await page.locator('#profile-website').fill('https://example.org/portfolio');
    await page.locator('#profile-contact').fill('public@example.org');
    await page.locator('header [data-language]').selectOption('en');
    assert.equal(await page.locator('#team-name').inputValue(),'Название');
    assert.equal(await page.locator('#profile-description').inputValue(),'Черновик');
    assert.equal(await page.locator('#profile-card-preview h3').innerText(),'Название');
    assert.equal(await page.locator('#profile-card-preview .organization-description').first().innerText(),'Черновик');
    assert.equal(await page.locator('label[for="profile-description"]').innerText(),'About you');
    assert.equal(await page.locator('#profile-team-fields').isVisible(),false);
    // A real PNG generated by Chromium, then decoded and resized by the server.
    const png = await page.screenshot();
    await page.locator('#profile-file').setInputFiles({name:'profile.png',mimeType:'image/png',buffer:png});
    await wait(page,'#photo-status','Photo saved');
    assert(await page.locator('#profile-card-preview img').isVisible());
    await page.locator('#team-profile-form button[type="submit"]').click();
    await wait(page,'#profile-save-status','Profile saved');
    await page.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0);});
    await page.screenshot({path:path.join(out,'company-profile-desktop.png'),fullPage:true});
    await page.reload(); await page.waitForFunction(() => document.getElementById('team-name').value==='Название');
    assert.equal(await page.locator('header [data-language]').inputValue(),'en');
    assert(await page.locator('#profile-image img').isVisible());
    const profile = (await (await business.request.get(base+'/api/me/profile')).json()).profile;
    assert.equal(profile.description,'Черновик'); assert(profile.image_url.startsWith('/api/profile-images/'));
    for (const width of [390,375,320]) {
      await page.setViewportSize({width,height:844}); await overflow(page);
      assert(await page.locator('header [data-language]').isVisible());
      if(width===375) await page.screenshot({path:path.join(out,'company-profile-mobile.png'),fullPage:true});
    }
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('nav [data-view="create"]').click();
    await page.locator('#chat-input').fill('Несохранённое сообщение');
    await page.locator('#field-context').locator('..').locator('..').locator('summary').click();
    await page.locator('#field-context').fill('Ручной контекст');
    await page.locator('#confirm-context').check();
    await page.locator('header [data-language]').selectOption('ru');
    assert.equal(await page.locator('#chat-input').inputValue(),'Несохранённое сообщение');
    assert.equal(await page.locator('#field-context').inputValue(),'Ручной контекст');
    assert(await page.locator('#confirm-context').isChecked());
    await page.locator('header [data-language]').selectOption('en');
    const responsePromise = page.waitForRequest(r => r.url().endsWith('/messages') && r.method()==='POST');
    await page.locator('#send-message').click(); assert.equal((await responsePromise).postDataJSON().locale,'en');
    await page.waitForFunction(() => document.querySelectorAll('.chat-message.assistant').length>0);
    console.log('PASS bilingual UI, form preservation, profile image decoding/persistence, responsive profile, English chat locale');
    await teamPage.goto(base+'/app#team-profile');
    await teamPage.waitForFunction(() => !document.body.classList.contains('booting'));
    await teamPage.locator('#team-name').fill('Команда '+stamp);
    await teamPage.locator('#team-skills').fill('Analysis, Python');
    await teamPage.locator('#profile-description').fill('Команда исследователей и разработчиков.');
    await teamPage.locator('#profile-experience').fill('Аналитические отчёты и прототипы.');
    await teamPage.locator('#profile-file').setInputFiles({name:'team.png',mimeType:'image/png',buffer:png});
    await wait(teamPage,'#photo-status','Фото сохранено');
    await teamPage.locator('#team-profile-form button[type="submit"]').click();
    await wait(teamPage,'#profile-save-status','Профиль сохранён');
    const taskResponse = await business.request.post(base+'/api/me/tasks',{headers:{'X-CSRF-Token':csrf},data:{topic:'Retail',card:{title:'Compare proposal approaches','expected_result':'An analytical report','need':'Reduce waste'},confirmed_fields:[]}});
    const task = await taskResponse.json();
    await business.request.post(base+'/api/me/tasks/'+task.id+'/publish',{headers:{'X-CSRF-Token':csrf}});
    let pid;
    for (const [context,token,name] of [[team,teamCsrf,'Team'],[await browser.newContext(),null,'Second team']]) {
      const useToken = token || await register(context,'TEAM','profiles-second');
      if(!token) await context.request.put(base+'/api/me/profile',{headers:{'X-CSRF-Token':useToken},data:{name,skills:['UX']}});
      const proposal = await context.request.post(base+'/api/catalog/tasks/'+task.id+'/proposals',{headers:{'X-CSRF-Token':useToken},data:{idea:'Analyze the available data','plan':'Prepare an analytical report',duration_days:token?14:21,prototype_url:'https://example.org/report'}});
      assert.equal(proposal.status(),201); if(token) pid=(await proposal.json()).id;
    }
    await page.locator('nav [data-view="business"]').click();
    await page.locator('#business-task').selectOption(String(task.id));
    await page.waitForFunction(() => document.querySelectorAll('#proposal-comparison tbody tr').length===2);
    assert((await page.locator('#proposal-comparison').innerText()).includes('14 days'));
    const card = page.locator('#proposal-card-'+pid);
    await card.locator('.organization-card img').waitFor({state:'visible'});
    await card.locator('.proposal-review summary').click();
    await card.locator('.proposal-review button').click();
    await wait(page,'#proposal-card-'+pid+' .review-content','Which data will you use?');
    assert.equal(await card.locator('blockquote').innerText(),'Prepare an analytical report');
    const incoming = await business.request.get(base+'/api/me/tasks/'+task.id+'/proposals');
    assert((await incoming.json()).proposals.every(p => p.status==='pending'));
    await page.screenshot({path:path.join(out,'proposal-comparison-desktop.png'),fullPage:true});
    await page.reload(); await page.locator('#business-task').selectOption(String(task.id));
    await page.locator('#proposal-card-'+pid+' .proposal-review summary').click();
    await wait(page,'#proposal-card-'+pid+' .review-content','Which data will you use?');
    await page.locator('header [data-language]').selectOption('ru');
    assert.equal(await page.locator('#proposal-card-'+pid+' .proposal-review').getAttribute('open'),null);
    await page.locator('#proposal-card-'+pid+' .proposal-review summary').click();
    await page.locator('#proposal-card-'+pid+' .proposal-review button').click();
    await wait(page,'#proposal-card-'+pid+' .review-content','Какие данные');
    for(const width of [390,375,320]){await page.setViewportSize({width,height:844});await overflow(page);}
    await page.screenshot({path:path.join(out,'proposal-comparison-mobile.png'),fullPage:true});
    await page.route('**/api/auth/me',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'HTTP_ERROR',message:'Synthetic session failure'}})}));
    await page.goto(base+'/app?session-test=1#team-profile');
    await page.locator('#retry-session').waitFor({state:'visible'});
    await page.unroute('**/api/auth/me'); await page.locator('#retry-session').click();
    await page.waitForFunction(()=>!document.body.classList.contains('booting'));
    assert.deepEqual(errors,[]); console.log('PASS public team photos, comparison of two proposals, saved localized AI fixture review, no automatic decisions; no browser errors');
    console.log('Screenshots: '+out);
  } catch(error) {await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw error;}
  finally {await browser.close();}
})().catch(error => {console.error(error);process.exitCode=1;});
